# Generated by Django 5.0.4 on 2024-07-15 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detc', '0003_detectprofile_result_alter_detectprofile_is_happened'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectprofile',
            name='desc',
            field=models.CharField(max_length=4000, null=True),
        ),
    ]
