# Generated by Django 5.0.4 on 2024-07-17 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detc', '0004_detectprofile_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectprofile',
            name='sex',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
