# Generated by Django 5.0.4 on 2024-07-20 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detc', '0005_detectprofile_sex'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassifiProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('sex', models.CharField(blank=True, max_length=7, null=True)),
                ('resigned_hospital', models.TextField(blank=True, null=True)),
                ('is_happened', models.BooleanField(blank=True, default=False, null=True)),
                ('image', models.ImageField(upload_to='classifi_mri_upload/')),
                ('result', models.CharField(blank=True, max_length=225, null=True)),
                ('desc', models.CharField(max_length=4000, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
