# Generated by Django 5.0.4 on 2024-07-22 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detc', '0007_alter_classifiprofile_id_alter_detectprofile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classifiprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='detectprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
