# Generated by Django 4.1.13 on 2024-08-20 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detc', '0008_alter_classifiprofile_id_alter_detectprofile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detectprofile',
            name='is_happened',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
