# Generated by Django 4.1.13 on 2024-08-20 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detc', '0009_alter_detectprofile_is_happened'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classifiprofile',
            old_name='age',
            new_name='birth',
        ),
        migrations.RenameField(
            model_name='detectprofile',
            old_name='age',
            new_name='birth',
        ),
        migrations.AddField(
            model_name='classifiprofile',
            name='address',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='detectprofile',
            name='address',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='classifiprofile',
            name='desc',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='classifiprofile',
            name='is_happened',
            field=models.CharField(blank=True, default='False', max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='detectprofile',
            name='desc',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='detectprofile',
            name='image',
            field=models.ImageField(upload_to='classifi_mri_upload/'),
        ),
        migrations.AlterField(
            model_name='detectprofile',
            name='is_happened',
            field=models.CharField(blank=True, default='False', max_length=7, null=True),
        ),
    ]
