# Generated by Django 4.1.13 on 2024-08-20 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detc', '0010_rename_age_classifiprofile_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classifiprofile',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detectprofile',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
